name: Build, Push to ACR, and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: mycontainerregistrysmall      # your Azure Container Registry name (without .azurecr.io)
  IMAGE_NAME: flask-eval
  AKS_CLUSTER_NAME: myAKSClusterSmallNew     # your AKS cluster name
  AKS_RESOURCE_GROUP: myResourceGroup     # your AKS resource group

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Set up Docker login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build and push Docker image to ACR
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE=$ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

      - name: Deploy to AKS
       uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            ${{ env.IMAGE }}

