name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: mycontainerregistrysmall
  IMAGE_NAME: flask-eval

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name $REGISTRY_NAME

    - name: Build and push image to ACR
      run: |
        IMAGE_TAG=${{ github.run_number }}
        az acr build \
          --registry $REGISTRY_NAME \
          --image $IMAGE_NAME:$IMAGE_TAG .

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: myAKSClusterSmall
        resource-group: myResourceGroup

    - name: Deploy manifests to AKS
      run: |
        kubectl set image deployment/flask-k8s-eval flask-container=$REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.run_number }} --record
        kubectl apply -f manifests/
